kind = "mobile"
previewPath = "/"
title = "UnKnot"
version = "1.0.0"
id = "artifacts/unknot"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23220

[services.development]
run = "pnpm --filter @workspace/unknot run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/unknot", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/unknot", "run", "serve" ]

[services.env]
PORT = "23220"
BASE_PATH = "/"
